#
# This is the default Travis CI configuration.
#
# It uses a GitHub OAuth token when fetching composer dependencies
# to avoid IP-based API throttling.
#
# It also allows publication of artifacts via an additional build.
#
language: php

php: ["5.3", "5.4", "5.5"]

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.4
    - secure: "qzYk+J6Z8AJJiGG7q9qXH1aUXUuQvIdidY9OjoiK61NGzDdEmfT/X8Ou+Hr+qWo8GQBykWaE+hxqJjiYhqXUsasckplUIM+nbd7NIg3fLTd92imAkAN3mBQ3GahFXJ5cCB0JwN3aab/qH8ItLuDOVHABuaszDxhznM1icaiIzsA="

install:
  - ./.travis.install
script:
  - ./vendor/bin/archer travis:build
